# Generated by Django 4.2.6 on 2023-10-29 15:23

from django.db import migrations, models
import events.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=200)),
                ('description', models.TextField(help_text='description', max_length=1000)),
                ('url', models.URLField(help_text='url')),
                ('date', models.DateField(help_text='date')),
                ('time', models.TimeField(help_text='time')),
                ('local_name', models.CharField(help_text='local name', max_length=50)),
                ('state', models.CharField(help_text='state', max_length=50)),
                ('city', models.CharField(help_text='city', max_length=50)),
                ('neighborhood', models.CharField(help_text='neighborhood', max_length=50)),
                ('street', models.CharField(help_text='street', max_length=50)),
                ('number', models.IntegerField(help_text='number')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.upload_event_iamge)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=50)),
                ('events', models.ManyToManyField(to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=50)),
                ('subtypes', models.ManyToManyField(to='events.eventsubtype')),
            ],
        ),
    ]
