# Generated by Django 4.2.6 on 2023-10-29 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubtype',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventsubtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='events.eventsubtype'),
        ),
    ]
