# Generated by Django 4.2.6 on 2023-10-29 02:55

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_event_iamge),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(help_text='city', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='neighborhood',
            field=models.CharField(help_text='neighborhood', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.IntegerField(help_text='number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(help_text='state', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(help_text='street', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(help_text='url'),
        ),
    ]
